#!/bin/bash
set -u
set -e
source globals
echo "========================================================================"
echo "Phase 5: Compilation des paquetages"
echo "========================================================================"

function build_binutils
{
	echo -n
	echo "() ====> Compilation de binutils"
	echo -n
	
	echo "Appliquer le ou les correctifs sur les sources"
	cd ./binutils-2.24/
	#Attention, ces correctifs seront utilisés pour la passe 2
	#patch -Np1 -i ../binutils-2.24-load_gcc_lto_plugin_by_default-1.patch
	#patch -Np1 -i ../binutils-2.24-lto_testsuite-1.patch
	cd ..

	echo "La documentation binutils recommande que ce paquetage soit compilé hors"
	echo "du répertoire sources"
	cd $LFS_SOURCES
	mkdir -v $LFS_SOURCES/binutils-build
	cd $LFS_SOURCES/binutils-build

	time (							
	../binutils-2.24/configure 		\
		--prefix=/tools				\
		--with-sysroot=$LFS			\
		--with-lib-path=/tools/lib	\
		--target=$LFS_TGT			\
		--disable-nls				\
		--disable-werror			\
		&& make && make install
	)
}

function build_gcc
{
	echo -n
	echo "() ====> Compilation de gcc"
	echo -n
	
	echo "gcc a besoin des paquetages gmp, mpfr et mpc."
	echo "Ces paquetages sont compilés ici pendant la compilation de gcc."
	echo "Les paquetages requis sont déplacés dans les sources de gcc."
	mv -v mpfr-3.1.2 ./gcc-4.9.1/mpfr
	mv -v gmp-6.0.0 ./gcc-4.9.1/gmp
	mv -v mpc-1.0.2 ./gcc-4.9.1/mpc
	
	echo "Modification des sources de gcc pour utiliser /tools"
	cd ./gcc-4.9.1
	for file in \
		$(find gcc/config -name linux64.h -o -name linux.h -o -name sysv4.h)
	do
		cp -uv $file{,.orig}
		sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
			-e 's@/usr@/tools@g' $file.orig > $file
		echo '
	#undef STANDARD_STARTFILE_PREFIX_1
	#undef STANDARD_STARTFILE_PREFIX_2
	#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
	#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
		touch $file.orig
	done
	
	echo "Modif reco LFS1"
	sed -i '/k prot/agcc_cv_libc_provides_ssp=yes' gcc/configure
	
	echo "Modif reco LFS1"
	sed -i 's/if \((code.*))\)/if (\1 \&\& \!DEBUG_INSN_P (insn))/' gcc/sched-deps.c
	
	echo "La documentation gcc recommande que ce paquetage soit compilé hors"
	echo "du répertoire sources"
	mkdir -v ../gcc-build
	cd ../gcc-build
	
	time (
	../gcc-4.9.1/configure									\
		--target=$LFS_TGT									\
		--prefix=/tools										\
		--with-sysroot=$LFS									\
		--with-newlib										\
		--without-headers									\
		--with-local-prefix=/tools							\
		--with-native-system-header-dir=/tools/include		\
		--disable-nls										\
		--disable-shared									\
		--disable-multilib									\
		--disable-decimal-float								\
		--disable-threads									\
		--disable-libatomic									\
		--disable-libgomp									\
		--disable-libitm									\
		--disable-libquadmath								\
		--disable-libsanitizer								\
		--disable-libssp									\
		--disable-libvtv									\
		--disable-libcilkrts								\
		--disable-libstdc++-v3								\
		--enable-languages=c,c++							\
		&& make && make install
	)
}


cd $LFS_SOURCES
#build_binutils
build_gcc
