#!/bin/bash
set -u
set -e
source globals
source source_repo
echo "========================================================================"
echo "Phase 2: Téléchargement et build des binaires de base"
echo "Téléchargement dans $LFS"
echo "========================================================================"

mkdir $LFS_SOURCES
for i in ${SOURCE_REPO[*]}
do
	wget -P $LFS/sources $i
done

for i in ${PATCH_REPO[*]}
do
	wget -P $LFS/sources $i
done
