#!/bin/bash
source globals
source source_repo
echo "========================================================================"
echo "Phase 2: Téléchargement et build des binaires de base"
echo "Téléchargement dans $LFS"
echo "========================================================================"

for i in ${SOURCE_REPO[*]}
do
	wget -P $LFS/sources $i
done

for i in ${PATCH_REPO[*]}
do
	wget -P $LFS/sources $i
done
