#!/bin/bash
source globals
echo "========================================================================"
echo "Phase 1: Création et formatage des partitions"
echo "========================================================================"
sudo fdisk -l /dev/sdb

echo "Trouver un moyen ici d'automatiser la création des partitions"
