#!/bin/bash

SOURCE_REPO=(
'http://download.savannah.gnu.org/releases/acl/acl-2.2.52.src.tar.gz'
'http://download.savannah.gnu.org/releases/attr/attr-2.4.47.src.tar.gz'
'http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz'
'http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz'
'http://alpha.gnu.org/gnu/bc/bc-1.06.95.tar.bz2'
'http://ftp.gnu.org/gnu/binutils/binutils-2.24.tar.bz2'
'http://ftp.gnu.org/gnu/bison/bison-3.0.2.tar.xz'
'http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz'
'http://sourceforge.net/projects/check/files/check/0.9.14/check-0.9.14.tar.gz'
'http://ftp.gnu.org/gnu/coreutils/coreutils-8.23.tar.xz'
'http://ftp.gnu.org/gnu/dejagnu/dejagnu-1.5.1.tar.gz'
'http://ftp.gnu.org/gnu/diffutils/diffutils-3.3.tar.xz'
'http://dev.gentoo.org/~blueness/eudev/eudev-1.10.tar.gz'
'http://anduin.linuxfromscratch.org/sources/other/eudev-1.10-manpages.tar.bz2'
'http://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.42.12/e2fsprogs-1.42.12.tar.gz'
'http://prdownloads.sourceforge.net/expat/expat-2.1.0.tar.gz'
'http://prdownloads.sourceforge.net/expect/expect5.45.tar.gz'
'ftp://ftp.astron.com/pub/file/file-5.19.tar.gz'
'http://ftp.gnu.org/gnu/findutils/findutils-4.4.2.tar.gz'
'http://prdownloads.sourceforge.net/flex/flex-2.5.39.tar.bz2'
'http://ftp.gnu.org/gnu/gawk/gawk-4.1.1.tar.xz'
'http://ftp.gnu.org/gnu/gcc/gcc-4.9.1/gcc-4.9.1.tar.bz2'
'http://ftp.gnu.org/gnu/gdbm/gdbm-1.11.tar.gz'
)

